// Package management provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package management

// ContentType defines model for Content-Type.
type ContentType string

// Approvals defines model for approvals.
type Approvals string

// Asc defines model for asc.
type Asc string

// AscFieldUid defines model for asc_field_uid.
type AscFieldUid string

// AssetType defines model for asset_type.
type AssetType string

// AssetUid defines model for asset_uid.
type AssetUid string

// Authorization defines model for authorization.
type Authorization string

// Authtoken defines model for authtoken.
type Authtoken string

// ContentTypeUid defines model for content_type_uid.
type ContentTypeUid string

// CustomFieldUid defines model for custom_field_uid.
type CustomFieldUid string

// DeleteAllLocalized defines model for delete_all_localized.
type DeleteAllLocalized string

// Desc defines model for desc.
type Desc string

// DescFieldUid defines model for desc_field_uid.
type DescFieldUid string

// EntryUid defines model for entry_uid.
type EntryUid string

// Environment defines model for environment.
type Environment string

// Folder defines model for folder.
type Folder string

// FolderUid defines model for folder_uid.
type FolderUid string

// Force defines model for force.
type Force string

// GlobalFieldUid defines model for global_field_uid.
type GlobalFieldUid string

// IncludeCollaborators defines model for include_collaborators.
type IncludeCollaborators string

// IncludeCount defines model for include_count.
type IncludeCount string

// IncludeDiscreteVariables defines model for include_discrete_variables.
type IncludeDiscreteVariables string

// IncludeFolders defines model for include_folders.
type IncludeFolders string

// IncludeGlobalFieldSchema defines model for include_global_field_schema.
type IncludeGlobalFieldSchema string

// IncludeGlobalFields defines model for include_global_fields.
type IncludeGlobalFields string

// IncludeInvitedBy defines model for include_invited_by.
type IncludeInvitedBy string

// IncludePath defines model for include_path.
type IncludePath string

// IncludePlan defines model for include_plan.
type IncludePlan string

// IncludePublishDetails defines model for include_publish_details.
type IncludePublishDetails string

// IncludeRoles defines model for include_roles.
type IncludeRoles string

// IncludeStackRoles defines model for include_stack_roles.
type IncludeStackRoles string

// IncludeStackVariables defines model for include_stack_variables.
type IncludeStackVariables string

// IncludeUserDetails defines model for include_user_details.
type IncludeUserDetails string

// IncludeWorkflow defines model for include_workflow.
type IncludeWorkflow string

// Limit defines model for limit.
type Limit float32

// Locale defines model for locale.
type Locale string

// LogUid defines model for log_uid.
type LogUid string

// Named defines model for named.
type Named string

// OrganizationUid defines model for organization_uid.
type OrganizationUid string

// Overwrite defines model for overwrite.
type Overwrite string

// OwnershipToken defines model for ownership_token.
type OwnershipToken string

// Query defines model for query.
type Query string

// RelativeUrls defines model for relative_urls.
type RelativeUrls string

// ShareUid defines model for share_uid.
type ShareUid string

// Skip defines model for skip.
type Skip float32

// SkipWorkflowStageCheck defines model for skip_workflow_stage_check.
type SkipWorkflowStageCheck string

// Typeahead defines model for typeahead.
type Typeahead string

// Uid defines model for uid.
type Uid string

// UserActivationToken defines model for user_activation_token.
type UserActivationToken string

// Version defines model for version.
type Version float32

// VersionNumber defines model for version_number.
type VersionNumber string

// XBulkAction defines model for x-bulk-action.
type XBulkAction string

// GetallassetsParams defines parameters for Getallassets.
type GetallassetsParams struct {
	// Enter either the UID of a specific folder to get the assets of that folder, or enter ‘cs_root’ to get all assets and their folder details from the root folder.
	Folder *Folder `json:"folder,omitempty"`

	// Set this parameter to ‘true’ to include the details of the created folders along with the details of the assets.
	IncludeFolders *IncludeFolders `json:"include_folders,omitempty"`

	// Enter the name of the environment to retrieve the assets published on them. You can enter multiple environments.
	Environment Environment `json:"environment"`

	// The Get a single folder by name call retrieves a specific asset folder based on the name provided.
	Query *string `json:"query,omitempty"`

	// Specify the version number of the asset that you want to retrieve. If the version is not specified, the details of the latest version will be retrieved.
	Version *float32 `json:"version,omitempty"`

	// Enter 'true' to include the publish details of the entry.
	IncludePublishDetails *string `json:"include_publish_details,omitempty"`

	// Set this parameter to 'true' to include the total number of assets available in your stack in the response body.
	IncludeCount *string `json:"include_count,omitempty"`

	// Set this to 'true' to display the relative URL of the asset.
	RelativeUrls RelativeUrls `json:"relative_urls"`

	// Enter the unique ID of the field for sorting the assets in ascending order by that field.
	AscFieldUid AscFieldUid `json:"asc_field_uid"`

	// Enter the unique ID of the field for sorting the assets in descending order by that field.
	DescFieldUid DescFieldUid `json:"desc_field_uid"`
	ApiKey       string       `json:"api_key"`
	Authtoken    *string      `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UploadassetParams defines parameters for Uploadasset.
type UploadassetParams struct {
	// Set this to 'true' to display the relative URL of the asset.
	RelativeUrls string `json:"relative_urls"`
	ApiKey       string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetanassetSpecificParams defines parameters for GetanassetSpecific.
type GetanassetSpecificParams struct {
	// Set this parameter to ‘true’ to include the asset folders in the search query.
	IncludeFolders bool `json:"include_folders"`

	// Enter the UID of the asset folder.
	Folder    string  `json:"folder"`
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// CreateafolderJSONBody defines parameters for Createafolder.
type CreateafolderJSONBody string

// CreateafolderParams defines parameters for Createafolder.
type CreateafolderParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteafolderParams defines parameters for Deleteafolder.
type DeleteafolderParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetasinglefolderParams defines parameters for Getasinglefolder.
type GetasinglefolderParams struct {
	// Set this parameter to ‘true’ to retrieve the complete path of the folder. The path will be displayed as an array of objects which includes the names and UIDs of each parent folder.
	IncludePath string `json:"include_path"`
	ApiKey      string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateormovefolderJSONBody defines parameters for Updateormovefolder.
type UpdateormovefolderJSONBody string

// UpdateormovefolderParams defines parameters for Updateormovefolder.
type UpdateormovefolderParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetinformationonRTEassetsParams defines parameters for GetinformationonRTEassets.
type GetinformationonRTEassetsParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GeteitheronlyimagesorvideosParams defines parameters for Geteitheronlyimagesorvideos.
type GeteitheronlyimagesorvideosParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteassetParams defines parameters for Deleteasset.
type DeleteassetParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetanassetParams defines parameters for Getanasset.
type GetanassetParams struct {
	// Set this parameter to ‘true’ to retrieve the complete path of the folder. The path will be displayed as an array of objects which includes the names and UIDs of each parent folder.
	IncludePath IncludePath `json:"include_path"`

	// Specify the version number of the asset that you want to retrieve. If the version is not specified, the details of the latest version will be retrieved.
	// Note: If no version is mentioned, this request will retrieve the latest published version of the asset. To retrieve a specific version, make use of the version parameter and keep the environment parameter blank.
	Version float32 `json:"version"`

	// Enter the name of the environment to retrieve assets published on&nbsp;them. You can enter multiple environments.
	EnvironmentName string `json:"environment_name"`

	// Enter the name of the environment to retrieve assets published on&nbsp;them. You can enter multiple environments.
	Environment string `json:"environment"`

	// Enter 'true' to include the publish details of the asset.
	IncludePublishDetails string `json:"include_publish_details"`

	// Set this to 'true' to display the relative URL of the asset. This parameter is not applicable when you delete an asset.
	RelativeUrls string `json:"relative_urls"`
	ApiKey       string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ReplaceassetJSONBody defines parameters for Replaceasset.
type ReplaceassetJSONBody interface{}

// ReplaceassetParams defines parameters for Replaceasset.
type ReplaceassetParams struct {
	// Enter the name of the environment if you wish to retrieve the assets published on a particular environment. You can enter multiple environments.
	Environment *string `json:"environment,omitempty"`

	// Set this to 'true' to display the relative URL of the asset. This parameter is not applicable when you delete an asset.
	RelativeUrls *string `json:"relative_urls,omitempty"`
	ApiKey       string  `json:"api_key"`
	Authtoken    *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// PublishanassetJSONBody defines parameters for Publishanasset.
type PublishanassetJSONBody string

// PublishanassetParams defines parameters for Publishanasset.
type PublishanassetParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetassetreferencesParams defines parameters for Getassetreferences.
type GetassetreferencesParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UnpublishanassetJSONBody defines parameters for Unpublishanasset.
type UnpublishanassetJSONBody string

// UnpublishanassetParams defines parameters for Unpublishanasset.
type UnpublishanassetParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetDetailsofAllVersionsofanAssetParams defines parameters for GetDetailsofAllVersionsofanAsset.
type GetDetailsofAllVersionsofanAssetParams struct {
	// Enter the number of version details to be skipped.
	Skip float32 `json:"skip"`

	// Enter the maximum number of version details to be returned.
	Limit float32 `json:"limit"`

	// Set to ‘true’ if you want to retrieve only the named versions of your asset.
	Named string `json:"named"`

	// Enter 'true' to get the total count of the asset version details.
	IncludeCount string `json:"include_count"`
	ApiKey       string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteVersionNameofAssetParams defines parameters for DeleteVersionNameofAsset.
type DeleteVersionNameofAssetParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// SetVersionNameforAssetJSONBody defines parameters for SetVersionNameforAsset.
type SetVersionNameforAssetJSONBody string

// SetVersionNameforAssetParams defines parameters for SetVersionNameforAsset.
type SetVersionNameforAssetParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteentriesandassetsinbulkJSONBody defines parameters for Deleteentriesandassetsinbulk.
type DeleteentriesandassetsinbulkJSONBody string

// DeleteentriesandassetsinbulkParams defines parameters for Deleteentriesandassetsinbulk.
type DeleteentriesandassetsinbulkParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// PublishanentrywithreferencesJSONBody defines parameters for Publishanentrywithreferences.
type PublishanentrywithreferencesJSONBody interface{}

// PublishanentrywithreferencesParams defines parameters for Publishanentrywithreferences.
type PublishanentrywithreferencesParams struct {
	// Set this to “true” to publish the entries that do not require an approval to be published.
	Approvals Approvals `json:"approvals"`

	// Pass “publish” as the value of this parameter in order to publish an entry with all references.
	XBulkAction *XBulkAction `json:"x-bulk-action,omitempty"`

	// Set this to “true” to publish the entries that are at a workflow stage where they satisfy the applied publish rules.
	SkipWorkflowStageCheck SkipWorkflowStageCheck `json:"skip_workflow_stage_check"`
	ApiKey                 string                 `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UnpublishentriesandassetsinbulkJSONBody defines parameters for Unpublishentriesandassetsinbulk.
type UnpublishentriesandassetsinbulkJSONBody string

// UnpublishentriesandassetsinbulkParams defines parameters for Unpublishentriesandassetsinbulk.
type UnpublishentriesandassetsinbulkParams struct {
	// Set this to 'true' to publish the entries that are at a workflow stage where they satisfy the applied publish rules.
	SkipWorkflowStageCheck string `json:"skip_workflow_stage_check"`

	// Set this to 'true' to publish the entries that do not require an approval to be published.
	Approvals string `json:"approvals"`
	ApiKey    string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateworkflowdetailsinbulkJSONBody defines parameters for Updateworkflowdetailsinbulk.
type UpdateworkflowdetailsinbulkJSONBody string

// UpdateworkflowdetailsinbulkParams defines parameters for Updateworkflowdetailsinbulk.
type UpdateworkflowdetailsinbulkParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallcontenttypesParams defines parameters for Getallcontenttypes.
type GetallcontenttypesParams struct {
	// Set this to 'true' to include in response the total count of content types available in your stack.
	IncludeCount string `json:"include_count"`

	// Set this to 'true' to include in response the details of all the fields within the Global field's schema.
	IncludeGlobalFieldSchema IncludeGlobalFieldSchema `json:"include_global_field_schema"`
	ApiKey                   string                   `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization Authorization `json:"authorization"`
	ContentType   string        `json:"Content-Type"`
}

// CreateacontenttypeJSONBody defines parameters for Createacontenttype.
type CreateacontenttypeJSONBody string

// CreateacontenttypeParams defines parameters for Createacontenttype.
type CreateacontenttypeParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// CreateContentTypewithExtensionFieldJSONBody defines parameters for CreateContentTypewithExtensionField.
type CreateContentTypewithExtensionFieldJSONBody interface{}

// CreateContentTypewithExtensionFieldParams defines parameters for CreateContentTypewithExtensionField.
type CreateContentTypewithExtensionFieldParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ImportacontenttypeParams defines parameters for Importacontenttype.
type ImportacontenttypeParams struct {
	// Select 'true' to replace the existing content type with the imported content type file.
	Overwrite Overwrite `json:"overwrite"`
	ApiKey    string    `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteContentTypeParams defines parameters for DeleteContentType.
type DeleteContentTypeParams struct {
	// Enter 'true' to force delete a content type.
	Force     Force   `json:"force"`
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetasinglecontenttypeParams defines parameters for Getasinglecontenttype.
type GetasinglecontenttypeParams struct {
	// Enter the version of the content type of which you want to retrieve the details. If no version is specified, you will get the latest version of the content type.
	Version Version `json:"version"`

	// Set this to 'true' to include in response the details of all the fields within the Global field's schema.
	IncludeGlobalFieldSchema string `json:"include_global_field_schema"`
	ApiKey                   string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateContentTypeJSONBody defines parameters for UpdateContentType.
type UpdateContentTypeJSONBody interface{}

// UpdateContentTypeParams defines parameters for UpdateContentType.
type UpdateContentTypeParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallentriesParams defines parameters for Getallentries.
type GetallentriesParams struct {
	// Enter the code of the language of which the entries needs to be included. Only the entries published in this locale will be displayed.
	Locale Locale `json:"locale"`

	// Enter 'true' to include the workflow details of the entry.
	IncludeWorkflow IncludeWorkflow `json:"include_workflow"`

	// Enter 'true' to include the publish details of the entry.
	IncludePublishDetails IncludePublishDetails `json:"include_publish_details"`
	ApiKey                string                `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// CreateanentryJSONBody defines parameters for Createanentry.
type CreateanentryJSONBody string

// CreateanentryParams defines parameters for Createanentry.
type CreateanentryParams struct {
	// Enter the code of the language in which you want your entry to be localized in.
	Locale string `json:"locale"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ImportanentryParams defines parameters for Importanentry.
type ImportanentryParams struct {
	// Enter the code of the language to import the entry of that particular language.
	Locale string `json:"locale"`

	// Select 'true' to replace an existing entry with the imported entry file.
	Overwrite string `json:"overwrite"`
	ApiKey    string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteanentryParams defines parameters for Deleteanentry.
type DeleteanentryParams struct {
	// Enter the code of the language of which the entry needs to be deleted.
	Locale string `json:"locale"`

	// Set the "delete_all_localized" parameter to "true" to delete all the localized versions of the entry.
	DeleteAllLocalized DeleteAllLocalized `json:"delete_all_localized"`
	ApiKey             string             `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetasingleentryParams defines parameters for Getasingleentry.
type GetasingleentryParams struct {
	// Enter the version number of the entry that you want to retrieve. However, to retrieve a specific version of an entry, you need to keep the environment parameter blank.
	Version *float32 `json:"version,omitempty"`

	// Enter the code of the language of which the entries need&nbsp;to be included. Only the entries published in this locale will be displayed.
	Locale *string `json:"locale,omitempty"`

	// Enter 'true' to include the workflow details of the entry.
	IncludeWorkflow *string `json:"include_workflow,omitempty"`

	// Enter 'true' to include the publish details of the entry.
	IncludePublishDetails *string `json:"include_publish_details,omitempty"`
	ApiKey                string  `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateanentryJSONBody defines parameters for Updateanentry.
type UpdateanentryJSONBody interface{}

// UpdateanentryParams defines parameters for Updateanentry.
type UpdateanentryParams struct {
	// Enter the code of the language of which the entry&nbsp;you need&nbsp;to update.
	Locale    *string `json:"locale,omitempty"`
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ExportanentryParams defines parameters for Exportanentry.
type ExportanentryParams struct {
	// Enter the code of the language to unlocalize the entry of that particular language.
	Locale string `json:"locale"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ImportanexistingentryParams defines parameters for Importanexistingentry.
type ImportanexistingentryParams struct {
	// Enter the code of the language to import the entry of that particular language.
	Locale string `json:"locale"`

	// Select 'true' to replace an existing entry with the imported entry file.
	Overwrite string `json:"overwrite"`
	ApiKey    string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetlanguagesofanentryParams defines parameters for Getlanguagesofanentry.
type GetlanguagesofanentryParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// PublishanentryJSONBody defines parameters for Publishanentry.
type PublishanentryJSONBody string

// PublishanentryParams defines parameters for Publishanentry.
type PublishanentryParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetreferencesofanentryParams defines parameters for Getreferencesofanentry.
type GetreferencesofanentryParams struct {
	// Enter the code of the language of which the entries needs to be included. Only the entries published in this locale will be displayed.
	Locale string `json:"locale"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UnlocalizeanentryJSONBody defines parameters for Unlocalizeanentry.
type UnlocalizeanentryJSONBody string

// UnlocalizeanentryParams defines parameters for Unlocalizeanentry.
type UnlocalizeanentryParams struct {
	// Enter the code of the language to unlocalize the entry of that particular language.
	Locale string `json:"locale"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UnpublishanentryJSONBody defines parameters for Unpublishanentry.
type UnpublishanentryJSONBody string

// UnpublishanentryParams defines parameters for Unpublishanentry.
type UnpublishanentryParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetDetailsofAllVersionsofanEntryParams defines parameters for GetDetailsofAllVersionsofanEntry.
type GetDetailsofAllVersionsofanEntryParams struct {
	// Enter the number of version details to be skipped.
	Skip float32 `json:"skip"`

	// Enter the maximum number of version details to be returned.
	Limit float32 `json:"limit"`

	// Set to ‘true’ if you want to retrieve only the named versions of your entry.
	Named Named `json:"named"`

	// Enter 'true' to get the total count of the entry version details.
	IncludeCount string `json:"include_count"`

	// Enter the code of the language of which the entries need to be included. Only the version details of entries published in this locale will be displayed.
	Locale string `json:"locale"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteVersionNameofEntryParams defines parameters for DeleteVersionNameofEntry.
type DeleteVersionNameofEntryParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// SetVersionNameforEntryJSONBody defines parameters for SetVersionNameforEntry.
type SetVersionNameforEntryJSONBody string

// SetVersionNameforEntryParams defines parameters for SetVersionNameforEntry.
type SetVersionNameforEntryParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// RequestAcceptRejectEntryPublishRequestJSONBody defines parameters for RequestAcceptRejectEntryPublishRequest.
type RequestAcceptRejectEntryPublishRequestJSONBody interface{}

// RequestAcceptRejectEntryPublishRequestParams defines parameters for RequestAcceptRejectEntryPublishRequest.
type RequestAcceptRejectEntryPublishRequestParams struct {
	Locale      *string `json:"locale,omitempty"`
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// ExportacontenttypeParams defines parameters for Exportacontenttype.
type ExportacontenttypeParams struct {
	// Enter the version of content type you want to retrieve. If no version is specified, you will get the latest version of the content type.
	Version float32 `json:"version"`
	ApiKey  string  `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallreferencesofcontenttypeParams defines parameters for Getallreferencesofcontenttype.
type GetallreferencesofcontenttypeParams struct {
	// Set the include_global_fields parameter to “true” to retrieve all the Global fields in which the specified content type is referenced.
	IncludeGlobalFields IncludeGlobalFields `json:"include_global_fields"`
	ApiKey              string              `json:"api_key"`

	// For this call we recommend you to use management token.
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetallcustomfieldsParams defines parameters for Getallcustomfields.
type GetallcustomfieldsParams struct {
	// For custom fields
	Query  Query  `json:"query"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// CreateaDashboardWidgetwithSourceURLJSONBody defines parameters for CreateaDashboardWidgetwithSourceURL.
type CreateaDashboardWidgetwithSourceURLJSONBody string

// CreateaDashboardWidgetwithSourceURLParams defines parameters for CreateaDashboardWidgetwithSourceURL.
type CreateaDashboardWidgetwithSourceURLParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallwidgetsParams defines parameters for Getallwidgets.
type GetallwidgetsParams struct {
	// Enter the UID of the content type of which you want to retrieve the details of all the applicable widgets
	Scope *string `json:"scope,omitempty"`

	// Parameter for&nbsp;custom widgets.
	Query  *string `json:"query,omitempty"`
	ApiKey string  `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UploadacustomfieldJSONBody defines parameters for Uploadacustomfield.
type UploadacustomfieldJSONBody interface{}

// UploadacustomfieldParams defines parameters for Uploadacustomfield.
type UploadacustomfieldParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeletecustomfieldParams defines parameters for Deletecustomfield.
type DeletecustomfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetasinglecustomfieldParams defines parameters for Getasinglecustomfield.
type GetasinglecustomfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateacustomfieldJSONBody defines parameters for Updateacustomfield.
type UpdateacustomfieldJSONBody string

// UpdateacustomfieldParams defines parameters for Updateacustomfield.
type UpdateacustomfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdatetheDashboardWidgetJSONBody defines parameters for UpdatetheDashboardWidget.
type UpdatetheDashboardWidgetJSONBody interface{}

// UpdatetheDashboardWidgetParams defines parameters for UpdatetheDashboardWidget.
type UpdatetheDashboardWidgetParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateawidgetJSONBody defines parameters for Updateawidget.
type UpdateawidgetJSONBody interface{}

// UpdateawidgetParams defines parameters for Updateawidget.
type UpdateawidgetParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallglobalfieldsParams defines parameters for Getallglobalfields.
type GetallglobalfieldsParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// CreateaglobalfieldJSONBody defines parameters for Createaglobalfield.
type CreateaglobalfieldJSONBody string

// CreateaglobalfieldParams defines parameters for Createaglobalfield.
type CreateaglobalfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ImportaglobalfieldParams defines parameters for Importaglobalfield.
type ImportaglobalfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeleteglobalfieldParams defines parameters for Deleteglobalfield.
type DeleteglobalfieldParams struct {
	// Set the force parameter to 'true' to delete the Global field.
	Force  string `json:"force"`
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetasingleglobalfieldParams defines parameters for Getasingleglobalfield.
type GetasingleglobalfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// UpdateaglobalfieldJSONBody defines parameters for Updateaglobalfield.
type UpdateaglobalfieldJSONBody string

// UpdateaglobalfieldParams defines parameters for Updateaglobalfield.
type UpdateaglobalfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// ExportaglobalfieldParams defines parameters for Exportaglobalfield.
type ExportaglobalfieldParams struct {
	ApiKey string `json:"api_key"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// SetafallbacklanguageJSONBody defines parameters for Setafallbacklanguage.
type SetafallbacklanguageJSONBody interface{}

// SetafallbacklanguageParams defines parameters for Setafallbacklanguage.
type SetafallbacklanguageParams struct {
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// GetallOrganizationsParams defines parameters for GetallOrganizations.
type GetallOrganizationsParams struct {
	// The ‘limit’ parameter will return a specific number of entries in the output. Example, if there are 10 organizations and you wish to fetch only the first 2, you need to specify '2' as the value in this parameter.
	Limit Limit `json:"limit"`

	// The ‘skip’ parameter will skip a specific number of organizations in the output. Example, if there are 12 organizations and you want to skip the first 2 to get only the last 10 in the response body, you need to specify ‘2’ here.
	Skip Skip `json:"skip"`

	// The ‘asc’ parameter allows you to sort the list of organizations in the ascending order with respect to the value of a specific field.
	Asc Asc `json:"asc"`

	// The ‘desc’ parameter allows you to sort the list of Organizations in the descending order with respect to the value of a specific field.
	Desc Desc `json:"desc"`

	// The ‘include_count’ parameter returns the total number of organizations related to the user. Example: If you wish to know the total number of organizations, you need to mention ‘true’.
	IncludeCount IncludeCount `json:"include_count"`

	// The typeahead parameter is a type of filter that allows you to perform a name-based search on all organizations based on the value provided. Example, if we have four organizations named ‘ABC’, ‘ABC1’, ‘XYZ’, and ‘ACC’, and we provide ‘ABC’ as the value to this parameter, the search result will return the organizations ‘ABC’ and ‘ABC1’ as the output.
	Typeahead   Typeahead `json:"typeahead"`
	Authtoken   *string   `json:"authtoken,omitempty"`
	ContentType string    `json:"Content-Type"`
}

// GetasingleOrganizationParams defines parameters for GetasingleOrganization.
type GetasingleOrganizationParams struct {
	// The include_plan parameter includes the details of the plan that the organization has subscribed to. To include the details of the subscribed plan in the Response body, enter ‘true’.
	IncludePlan IncludePlan `json:"include_plan"`
	Authtoken   *string     `json:"authtoken,omitempty"`
	ContentType string      `json:"Content-Type"`
}

// GetorganizationlogdetailsParams defines parameters for Getorganizationlogdetails.
type GetorganizationlogdetailsParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetorganizationlogitemParams defines parameters for Getorganizationlogitem.
type GetorganizationlogitemParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetallrolesinanOrganizationParams defines parameters for GetallrolesinanOrganization.
type GetallrolesinanOrganizationParams struct {
	// The ‘limit’ parameter will return a specific number of Organization roles in the output. Example, if there are 10 organization roles and you wish to fetch only the first 2, you need to specify '2' as the value in this parameter.
	Limit string `json:"limit"`

	// The ‘skip’ parameter will skip a specific number of Organization roles in the output. For example, if there are 12 organization roles and you want to skip the first 2 to get only the last 10 in the response body, you need to specify ‘2’ here.
	Skip string `json:"skip"`

	// The ‘asc’ parameter allows you to sort the list of organization roles in an ascending order on the basis of a parameter.
	Asc string `json:"asc"`

	// The ‘desc’ parameter allows you to sort the list of organization roles in a descending order on the basis of a parameter.
	Desc string `json:"desc"`

	// The ‘include_count’ parameter returns the total number of roles in an organization. For example: If you want to know the total number of roles in an organization, you need to mention ‘true’.
	IncludeCount string `json:"include_count"`

	// The ‘include_stack_roles’ parameter,&nbsp;when set to ‘true’, includes the details of stack-level roles in the Response body.
	IncludeStackRoles IncludeStackRoles `json:"include_stack_roles"`
	Authtoken         *string           `json:"authtoken,omitempty"`
	ContentType       string            `json:"Content-Type"`
}

// GetallOrganizationinvitationsParams defines parameters for GetallOrganizationinvitations.
type GetallOrganizationinvitationsParams struct {
	// The ‘limit’ parameter will return a specific number of sent organization invitations in the output. Example, if 10 invitations were sent out and you wish to fetch only the first 8, you need to specify '2' as the value in this parameter.
	Limit float32 `json:"limit"`

	// The ‘skip’ parameter will skip a specific number of organization roles in the output. Example, if there are 12 organization roles and you want to skip the last 2 to get only the first 10 in the response body, you need to specify ‘2’ here.
	Skip float32 `json:"skip"`

	// The ‘asc’ parameter allows you to sort the list of organization invitations in ascending order on the basis of a specific parameter.
	Asc string `json:"asc"`

	// The ‘desc’ parameter allows you to sort the list of organization invitations in descending order on the basis of a specific parameter.
	Desc string `json:"desc"`

	// The ‘include_count’ parameter returns the total number of organization invitations sent out. Example: If you wish to know the total number of organization invitations, you need to mention ‘true’.
	IncludeCount string `json:"include_count"`

	// The ‘include_roles’ parameter,&nbsp;when set to ‘true’, will display the details of the roles that are assigned to the user in an organization.
	IncludeRoles IncludeRoles `json:"include_roles"`

	// The ‘include_invited_by’ parameter, when set to ‘true’, includes the details of the user who sent out the organization invitation.
	IncludeInvitedBy IncludeInvitedBy `json:"include_invited_by"`

	// The ‘include_user_details’ parameter,&nbsp;when set to ‘true’, lets you know whether the user who has been sent the organization invitation has enabled Two-factor Authentication or not.
	IncludeUserDetails IncludeUserDetails `json:"include_user_details"`

	// The ‘typeahead’ parameter allows you to perform a name-based search on all the stacks on an organization based on the value provided. For example, it allows you to perform an email-ID-based search on all users based on the email ID provided.
	Typeahead   string  `json:"typeahead"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// AdduserstoOrganizationJSONBody defines parameters for AdduserstoOrganization.
type AdduserstoOrganizationJSONBody string

// AdduserstoOrganizationParams defines parameters for AdduserstoOrganization.
type AdduserstoOrganizationParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// ResendpendingOrganizationinvitationParams defines parameters for ResendpendingOrganizationinvitation.
type ResendpendingOrganizationinvitationParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetallstacksinanOrganizationParams defines parameters for GetallstacksinanOrganization.
type GetallstacksinanOrganizationParams struct {
	// The ‘limit’ parameter will return a specific number of stacks in the output. Example, if there are 10 organization stacks and you wish to fetch only the first 2, you need to specify '2' as value in this parameter.
	Limit string `json:"limit"`

	// The ‘skip’ parameter will skip a specific number of organization stacks in the output. Example, if there are 12 stacks and you want to skip the last 2 to get only the first 10 in the response body, you need to specify ‘2’ here.
	Skip string `json:"skip"`

	// The ‘asc’ parameter allows you to sort the list of stacks in an organization in the ascending order.
	Asc string `json:"asc"`

	// The ‘desc’ parameter allows you to sort the list of stacks in an organization in the descending order.
	Desc string `json:"desc"`

	// The ‘include_count’ parameter returns the total number of stacks in an organization. Example: If you wish to know the total number of stacks in your organization, you need to mention ‘true’.
	IncludeCount string `json:"include_count"`

	// The ‘typeahead’ parameter allows you to perform a name-based search on all the stacks on an organization based on the value provided.
	Typeahead   string  `json:"typeahead"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// TransferOrganizationownershipJSONBody defines parameters for TransferOrganizationownership.
type TransferOrganizationownershipJSONBody string

// TransferOrganizationownershipParams defines parameters for TransferOrganizationownership.
type TransferOrganizationownershipParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// DeletemultipleitemsfromaReleaseParams defines parameters for DeletemultipleitemsfromaRelease.
type DeletemultipleitemsfromaReleaseParams struct {
	All       string  `json:"all"`
	ApiKey    string  `json:"api_key"`
	Authtoken *string `json:"authtoken,omitempty"`

	// For this call we recommend you to use management token.
	Authorization string `json:"authorization"`
	ContentType   string `json:"Content-Type"`
}

// DeletestackParams defines parameters for Deletestack.
type DeletestackParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetasinglestackParams defines parameters for Getasinglestack.
type GetasinglestackParams struct {
	// Set this parameter to 'true' to include the details of the stack collaborators.
	IncludeCollaborators IncludeCollaborators `json:"include_collaborators"`

	// Set this to 'true' to display the stack variables. Stack variables are extra information about the stack, such as the description, format of date, format of time, and so on. Users can include or exclude stack variables in the response.
	IncludeStackVariables IncludeStackVariables `json:"include_stack_variables"`

	// Set this to 'true' to view the access token of your stack.
	IncludeDiscreteVariables IncludeDiscreteVariables `json:"include_discrete_variables"`

	// Set this to 'true' to include in the response the total count of the stacks owned by or shared with a user account.
	IncludeCount string  `json:"include_count"`
	ApiKey       *string `json:"api_key,omitempty"`
	Authtoken    *string `json:"authtoken,omitempty"`
	ContentType  string  `json:"Content-Type"`
}

// CreatestackJSONBody defines parameters for Createstack.
type CreatestackJSONBody string

// CreatestackParams defines parameters for Createstack.
type CreatestackParams struct {
	Authtoken       *string `json:"authtoken,omitempty"`
	OrganizationUid string  `json:"organization_uid"`
	ContentType     string  `json:"Content-Type"`
}

// UpdatestackJSONBody defines parameters for Updatestack.
type UpdatestackJSONBody string

// UpdatestackParams defines parameters for Updatestack.
type UpdatestackParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// AllUsersParams defines parameters for AllUsers.
type AllUsersParams struct {
	IncludeCollaborators bool    `json:"include_collaborators"`
	ApiKey               string  `json:"api_key"`
	Authtoken            *string `json:"authtoken,omitempty"`
	ContentType          string  `json:"Content-Type"`
}

// AcceptstackownedbyotheruserParams defines parameters for Acceptstackownedbyotheruser.
type AcceptstackownedbyotheruserParams struct {
	// Enter the stack API key.
	ApiKey string `json:"api_key"`

	// Enter the user uid.
	Uid         Uid    `json:"uid"`
	ContentType string `json:"Content-Type"`
}

// GetstacksettingsParams defines parameters for Getstacksettings.
type GetstacksettingsParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// AddstacksettingsJSONBody defines parameters for Addstacksettings.
type AddstacksettingsJSONBody string

// AddstacksettingsParams defines parameters for Addstacksettings.
type AddstacksettingsParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// ResetstackJSONBody defines parameters for Resetstack.
type ResetstackJSONBody string

// ResetstackParams defines parameters for Resetstack.
type ResetstackParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// ShareastackJSONBody defines parameters for Shareastack.
type ShareastackJSONBody string

// ShareastackParams defines parameters for Shareastack.
type ShareastackParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// TransferstackownershiptootherusersJSONBody defines parameters for Transferstackownershiptootherusers.
type TransferstackownershiptootherusersJSONBody string

// TransferstackownershiptootherusersParams defines parameters for Transferstackownershiptootherusers.
type TransferstackownershiptootherusersParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// UnshareastackJSONBody defines parameters for Unshareastack.
type UnshareastackJSONBody string

// UnshareastackParams defines parameters for Unshareastack.
type UnshareastackParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// UpdateUserRoleJSONBody defines parameters for UpdateUserRole.
type UpdateUserRoleJSONBody string

// UpdateUserRoleParams defines parameters for UpdateUserRole.
type UpdateUserRoleParams struct {
	ApiKey      string  `json:"api_key"`
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// GetuserParams defines parameters for Getuser.
type GetuserParams struct {
	Authtoken   Authtoken   `json:"authtoken"`
	ContentType ContentType `json:"Content-Type"`
}

// UpdateuserJSONBody defines parameters for Updateuser.
type UpdateuserJSONBody string

// UpdateuserParams defines parameters for Updateuser.
type UpdateuserParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// LogoutofyouraccountParams defines parameters for Logoutofyouraccount.
type LogoutofyouraccountParams struct {
	Authtoken   *string `json:"authtoken,omitempty"`
	ContentType string  `json:"Content-Type"`
}

// LogintoyouraccountJSONBody defines parameters for Logintoyouraccount.
type LogintoyouraccountJSONBody string

// LogintoyouraccountParams defines parameters for Logintoyouraccount.
type LogintoyouraccountParams struct {
	ContentType string `json:"Content-Type"`
}

// ActivateauseraccountJSONBody defines parameters for Activateauseraccount.
type ActivateauseraccountJSONBody string

// ActivateauseraccountParams defines parameters for Activateauseraccount.
type ActivateauseraccountParams struct {
	ContentType string `json:"Content-Type"`
}

// RequestforapasswordJSONBody defines parameters for Requestforapassword.
type RequestforapasswordJSONBody string

// RequestforapasswordParams defines parameters for Requestforapassword.
type RequestforapasswordParams struct {
	ContentType string `json:"Content-Type"`
}

// ResetpasswordJSONBody defines parameters for Resetpassword.
type ResetpasswordJSONBody string

// ResetpasswordParams defines parameters for Resetpassword.
type ResetpasswordParams struct {
	ContentType string `json:"Content-Type"`
}

// CreateafolderJSONRequestBody defines body for Createafolder for application/json ContentType.
type CreateafolderJSONRequestBody CreateafolderJSONBody

// UpdateormovefolderJSONRequestBody defines body for Updateormovefolder for application/json ContentType.
type UpdateormovefolderJSONRequestBody UpdateormovefolderJSONBody

// ReplaceassetJSONRequestBody defines body for Replaceasset for application/json ContentType.
type ReplaceassetJSONRequestBody ReplaceassetJSONBody

// PublishanassetJSONRequestBody defines body for Publishanasset for application/json ContentType.
type PublishanassetJSONRequestBody PublishanassetJSONBody

// UnpublishanassetJSONRequestBody defines body for Unpublishanasset for application/json ContentType.
type UnpublishanassetJSONRequestBody UnpublishanassetJSONBody

// SetVersionNameforAssetJSONRequestBody defines body for SetVersionNameforAsset for application/json ContentType.
type SetVersionNameforAssetJSONRequestBody SetVersionNameforAssetJSONBody

// DeleteentriesandassetsinbulkJSONRequestBody defines body for Deleteentriesandassetsinbulk for application/json ContentType.
type DeleteentriesandassetsinbulkJSONRequestBody DeleteentriesandassetsinbulkJSONBody

// PublishanentrywithreferencesJSONRequestBody defines body for Publishanentrywithreferences for application/json ContentType.
type PublishanentrywithreferencesJSONRequestBody PublishanentrywithreferencesJSONBody

// UnpublishentriesandassetsinbulkJSONRequestBody defines body for Unpublishentriesandassetsinbulk for application/json ContentType.
type UnpublishentriesandassetsinbulkJSONRequestBody UnpublishentriesandassetsinbulkJSONBody

// UpdateworkflowdetailsinbulkJSONRequestBody defines body for Updateworkflowdetailsinbulk for application/json ContentType.
type UpdateworkflowdetailsinbulkJSONRequestBody UpdateworkflowdetailsinbulkJSONBody

// CreateacontenttypeJSONRequestBody defines body for Createacontenttype for application/json ContentType.
type CreateacontenttypeJSONRequestBody CreateacontenttypeJSONBody

// CreateContentTypewithExtensionFieldJSONRequestBody defines body for CreateContentTypewithExtensionField for application/json ContentType.
type CreateContentTypewithExtensionFieldJSONRequestBody CreateContentTypewithExtensionFieldJSONBody

// UpdateContentTypeJSONRequestBody defines body for UpdateContentType for application/json ContentType.
type UpdateContentTypeJSONRequestBody UpdateContentTypeJSONBody

// CreateanentryJSONRequestBody defines body for Createanentry for application/json ContentType.
type CreateanentryJSONRequestBody CreateanentryJSONBody

// UpdateanentryJSONRequestBody defines body for Updateanentry for application/json ContentType.
type UpdateanentryJSONRequestBody UpdateanentryJSONBody

// PublishanentryJSONRequestBody defines body for Publishanentry for application/json ContentType.
type PublishanentryJSONRequestBody PublishanentryJSONBody

// UnlocalizeanentryJSONRequestBody defines body for Unlocalizeanentry for application/json ContentType.
type UnlocalizeanentryJSONRequestBody UnlocalizeanentryJSONBody

// UnpublishanentryJSONRequestBody defines body for Unpublishanentry for application/json ContentType.
type UnpublishanentryJSONRequestBody UnpublishanentryJSONBody

// SetVersionNameforEntryJSONRequestBody defines body for SetVersionNameforEntry for application/json ContentType.
type SetVersionNameforEntryJSONRequestBody SetVersionNameforEntryJSONBody

// RequestAcceptRejectEntryPublishRequestJSONRequestBody defines body for RequestAcceptRejectEntryPublishRequest for application/json ContentType.
type RequestAcceptRejectEntryPublishRequestJSONRequestBody RequestAcceptRejectEntryPublishRequestJSONBody

// CreateaDashboardWidgetwithSourceURLJSONRequestBody defines body for CreateaDashboardWidgetwithSourceURL for application/json ContentType.
type CreateaDashboardWidgetwithSourceURLJSONRequestBody CreateaDashboardWidgetwithSourceURLJSONBody

// UploadacustomfieldJSONRequestBody defines body for Uploadacustomfield for application/json ContentType.
type UploadacustomfieldJSONRequestBody UploadacustomfieldJSONBody

// UpdateacustomfieldJSONRequestBody defines body for Updateacustomfield for application/json ContentType.
type UpdateacustomfieldJSONRequestBody UpdateacustomfieldJSONBody

// UpdatetheDashboardWidgetJSONRequestBody defines body for UpdatetheDashboardWidget for application/json ContentType.
type UpdatetheDashboardWidgetJSONRequestBody UpdatetheDashboardWidgetJSONBody

// UpdateawidgetJSONRequestBody defines body for Updateawidget for application/json ContentType.
type UpdateawidgetJSONRequestBody UpdateawidgetJSONBody

// CreateaglobalfieldJSONRequestBody defines body for Createaglobalfield for application/json ContentType.
type CreateaglobalfieldJSONRequestBody CreateaglobalfieldJSONBody

// UpdateaglobalfieldJSONRequestBody defines body for Updateaglobalfield for application/json ContentType.
type UpdateaglobalfieldJSONRequestBody UpdateaglobalfieldJSONBody

// SetafallbacklanguageJSONRequestBody defines body for Setafallbacklanguage for application/json ContentType.
type SetafallbacklanguageJSONRequestBody SetafallbacklanguageJSONBody

// AdduserstoOrganizationJSONRequestBody defines body for AdduserstoOrganization for application/json ContentType.
type AdduserstoOrganizationJSONRequestBody AdduserstoOrganizationJSONBody

// TransferOrganizationownershipJSONRequestBody defines body for TransferOrganizationownership for application/json ContentType.
type TransferOrganizationownershipJSONRequestBody TransferOrganizationownershipJSONBody

// CreatestackJSONRequestBody defines body for Createstack for application/json ContentType.
type CreatestackJSONRequestBody CreatestackJSONBody

// UpdatestackJSONRequestBody defines body for Updatestack for application/json ContentType.
type UpdatestackJSONRequestBody UpdatestackJSONBody

// AddstacksettingsJSONRequestBody defines body for Addstacksettings for application/json ContentType.
type AddstacksettingsJSONRequestBody AddstacksettingsJSONBody

// ResetstackJSONRequestBody defines body for Resetstack for application/json ContentType.
type ResetstackJSONRequestBody ResetstackJSONBody

// ShareastackJSONRequestBody defines body for Shareastack for application/json ContentType.
type ShareastackJSONRequestBody ShareastackJSONBody

// TransferstackownershiptootherusersJSONRequestBody defines body for Transferstackownershiptootherusers for application/json ContentType.
type TransferstackownershiptootherusersJSONRequestBody TransferstackownershiptootherusersJSONBody

// UnshareastackJSONRequestBody defines body for Unshareastack for application/json ContentType.
type UnshareastackJSONRequestBody UnshareastackJSONBody

// UpdateUserRoleJSONRequestBody defines body for UpdateUserRole for application/json ContentType.
type UpdateUserRoleJSONRequestBody UpdateUserRoleJSONBody

// UpdateuserJSONRequestBody defines body for Updateuser for application/json ContentType.
type UpdateuserJSONRequestBody UpdateuserJSONBody

// LogintoyouraccountJSONRequestBody defines body for Logintoyouraccount for application/json ContentType.
type LogintoyouraccountJSONRequestBody LogintoyouraccountJSONBody

// ActivateauseraccountJSONRequestBody defines body for Activateauseraccount for application/json ContentType.
type ActivateauseraccountJSONRequestBody ActivateauseraccountJSONBody

// RequestforapasswordJSONRequestBody defines body for Requestforapassword for application/json ContentType.
type RequestforapasswordJSONRequestBody RequestforapasswordJSONBody

// ResetpasswordJSONRequestBody defines body for Resetpassword for application/json ContentType.
type ResetpasswordJSONRequestBody ResetpasswordJSONBody

